[package]
authors = ["Jacob Brown <kardeiz@gmail.com>"]
name = "rayon-issue"
version = "0.1.0"

[dependencies]
rayon = "0.6.0"
rust-crypto = "0.2.36"
serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"
